import { redirect } from "next/navigation";
import { AuthCard } from "../../../components/auth-card";
import { ResetPasswordForm } from "../../../components/reset-password-form";

export default async function ResetPasswordPage({
  searchParams
}: {
  searchParams: Promise<{ token?: string }>;
}) {
  const { token } = await searchParams;
  if (!token) {
    redirect("/forgot-password");
  }

  return (
    <AuthCard
      title="Choose a new password"
      description="Use the token issued by the backend reset flow to securely set a new password."
      footer={<span>The token is supplied through the reset link generated by the system.</span>}
    >
      <ResetPasswordForm token={token} />
    </AuthCard>
  );
}
